### ISSUE TITLE
Leaflet plugin with layerControl

### ISSUE THREAD

**Issue by dgplacenames** [allmaps/allmaps#143]
When using warpedMapLayer as an overlay with layerControl, the overlay layer disappears when reselected after being deselected. The layer returns on zoom in/out.
Example here: https://dgplacenames.github.io/maps/wigton1782

**Comment by sammeltassen** [comment]
This is indeed a know issue. It depends on how you instantiate the `warpedMapLayer`. If you do something like:

```
```

**Comment by sammeltassen** [comment]
This is indeed a know issue, and we plan to release a new version of the Leaflet plugin soon that should fix this.

It partly depends on how you instantiate the `warpedMapLayer`. If you'd add layers using a function like this:

```js
async function addWarpedMapLayer(annotationUrl) {
const layer = new AllmapsLeaflet.WarpedMapLayer()
await layer.addGeoreferenceAnnotationByUrl(annotationUrl)
return layer
}
```

This seems to cause no problem with the `layerControl` (see [this example](https://observablehq.com/@tudelft/kraijenhoff-was-here)), but it causes another issue with the initial rendering of the `warpedMapLayer` (that can be triggered manually with `WarpedMapLayer._update()`).

**Comment by dgplacenames** [comment]
Thank you.

**Comment by sammeltassen** [comment]
@dgplacenames This should now be fixed with the latest leaflet plugin (1.0.0-beta.40). Can you give it a try?

**Comment by dgplacenames** [comment]
I'm still getting the same issue as before. I've not instantiated `warpedMapLayer` using the function you suggest above. Do I still need to?
https://dgplacenames.github.io/maps/wigtownshire1782

**Comment by sammeltassen** [comment]
I have not seen this issue anymore with the latest versions of @allmaps/leaflet. Is it still occurring on your end @dgplacenames? If so, can you provide an example?
